env:
  browser: true
  es2021: true
extends:
  - plugin:react-hooks/recommended
  - airbnb-typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  {
    react/react-in-jsx-scope: off,
    react-hooks/rules-of-hooks: error,
    react-hooks/exhaustive-deps: warn,
    import/extensions: off,
    import/no-extraneous-dependencies: off
  }
