version: '3.9'
services:
  frontend:
    container_name: share-po-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:3000"
    stdin_open: true
  backend:
    container_name: share-po-backend
    build:
      context: ./backend
    volumes:
      - ./backend/:/api
    ports:
      - "1991:1991"
    volumes:
      - ./backend:/api
    working_dir: /api
    tty: true
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/server/main.go'
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: share-po-swagger-ui
    depends_on:
      - backend
    environment:
      - SWAGGER_URL=./openapi2.yaml
      - SWAGGER_JSON=/swagger/openapi2.yaml
    ports:
      - 8080:8080
    volumes:
      - ./swagger/:/swagger