version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:3000"
    stdin_open: true
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/:/api
    ports:
      - "1991:1991"
    volumes:
      - ./backend:/api
    working_dir: /api
    tty: false
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/server/main.go'