/* tslint:disable */
/* eslint-disable */
/**
 * share-po
 * ポートフォリオを共有、評価できるサイトです
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioStatus
 */
export interface PortfolioStatus {
    /**
     * 
     * @type {number}
     * @memberof PortfolioStatus
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioStatus
     */
    text?: string;
}

/**
 * Check if a given object implements the PortfolioStatus interface.
 */
export function instanceOfPortfolioStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortfolioStatusFromJSON(json: any): PortfolioStatus {
    return PortfolioStatusFromJSONTyped(json, false);
}

export function PortfolioStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function PortfolioStatusToJSON(value?: PortfolioStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'text': value.text,
    };
}

