/* tslint:disable */
/* eslint-disable */
/**
 * share-po
 * ポートフォリオを共有、評価できるサイトです
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioRequest
 */
export interface PortfolioRequest {
    /**
     * 
     * @type {string}
     * @memberof PortfolioRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof PortfolioRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    status?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof PortfolioRequest
     */
    tags?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PortfolioRequest
     */
    githubLink?: string;
    /**
     * 
     * @type {string}
     * @memberof PortfolioRequest
     */
    shareLink?: string;
}

/**
 * Check if a given object implements the PortfolioRequest interface.
 */
export function instanceOfPortfolioRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortfolioRequestFromJSON(json: any): PortfolioRequest {
    return PortfolioRequestFromJSONTyped(json, false);
}

export function PortfolioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'githubLink': !exists(json, 'githubLink') ? undefined : json['githubLink'],
        'shareLink': !exists(json, 'shareLink') ? undefined : json['shareLink'],
    };
}

export function PortfolioRequestToJSON(value?: PortfolioRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'userId': value.userId,
        'description': value.description,
        'status': value.status,
        'tags': value.tags,
        'githubLink': value.githubLink,
        'shareLink': value.shareLink,
    };
}

