/* tslint:disable */
/* eslint-disable */
/**
 * share-po
 * ポートフォリオを共有、評価できるサイトです
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PortfolioStatus,
} from '../models';
import {
    PortfolioStatusFromJSON,
    PortfolioStatusToJSON,
} from '../models';

/**
 * 
 */
export class PortfolioStatusApi extends runtime.BaseAPI {

    /**
     * ポートフォリオに設定できるステータスを一覧で取得します
     * ポートフォリオステータス取得
     */
    async getPortfolioStatusListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PortfolioStatus>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/portfolio-statuses`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PortfolioStatusFromJSON));
    }

    /**
     * ポートフォリオに設定できるステータスを一覧で取得します
     * ポートフォリオステータス取得
     */
    async getPortfolioStatusList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PortfolioStatus>> {
        const response = await this.getPortfolioStatusListRaw(initOverrides);
        return await response.value();
    }

}
